import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ComponentProvider";
import Header from "@/components/shared/Header";
import { Toaster } from "@/components/ui/toaster";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jobs At Start",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {" "}
      <head>
        <link
          rel="icon"
          href="https://cdn.prod.website-files.com/5fb2dd371e5ff1a34480d61e/660d7ba849081103918caf03_favicon-32x32.png"
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
